/-
  Abstractfeld.Tensor.Verified
  Batch-verified tensor identities — generated by the Abstractfeld flywheel.
  Each theorem is axiom-free, sorry-free, backed by Mathlib AlternatingMap.
-/
import Abstractfeld.Tensor.Interpret

namespace Abstractfeld.Tensor

open Abstractfeld.IR

variable {M : Type*} [AddCommGroup M] [Module ℚ M]

/-! ## Rank-2 identities -/

/-- Rank-2 antisymmetry: f(a,b) = -f(b,a) -/
theorem rank2_antisym (f : AlternatingMap ℚ M ℚ (Fin 2)) (v : Fin 2 → M) :
    f (v ∘ Equiv.swap 0 1) = -(f v) :=
  f.map_swap v (by decide)

/-- Rank-2 cancellation: f(a,b) + f(b,a) = 0 -/
theorem rank2_cancel (f : AlternatingMap ℚ M ℚ (Fin 2)) (v : Fin 2 → M) :
    f v + f (v ∘ Equiv.swap 0 1) = 0 :=
  f.map_add_swap v (by decide)

/-- Rank-2 diagonal vanishing: f(a,a) = 0 -/
theorem rank2_diag_zero (f : AlternatingMap ℚ M ℚ (Fin 2)) (v : Fin 2 → M)
    (h : v 0 = v 1) : f v = 0 :=
  f.map_eq_zero_of_eq v h (by decide)

/-! ## Rank-3 identities -/

/-- Rank-3 swap(0,1): f(b,a,c) = -f(a,b,c) -/
theorem rank3_swap01 (f : AlternatingMap ℚ M ℚ (Fin 3)) (v : Fin 3 → M) :
    f (v ∘ Equiv.swap 0 1) = -(f v) :=
  f.map_swap v (by decide)

/-- Rank-3 swap(1,2): f(a,c,b) = -f(a,b,c) -/
theorem rank3_swap12 (f : AlternatingMap ℚ M ℚ (Fin 3)) (v : Fin 3 → M) :
    f (v ∘ Equiv.swap 1 2) = -(f v) :=
  f.map_swap v (by decide)

/-- Rank-3 swap(0,2): f(c,b,a) = -f(a,b,c) -/
theorem rank3_swap02 (f : AlternatingMap ℚ M ℚ (Fin 3)) (v : Fin 3 → M) :
    f (v ∘ Equiv.swap 0 2) = -(f v) :=
  f.map_swap v (by decide)

/-- Rank-3 cyclic: the cyclic permutation (012→120) is even, so f is preserved. -/
theorem rank3_cyclic (f : AlternatingMap ℚ M ℚ (Fin 3)) (v : Fin 3 → M) :
    let σ : Equiv.Perm (Fin 3) := Equiv.swap 0 1 * Equiv.swap 1 2
    f (v ∘ σ) = f v := by
  intro σ
  rw [f.map_perm v σ]
  have : σ.sign = 1 := by decide
  rw [this, one_smul]

/-! ## Rank-4 additional identities -/

/-- Rank-4 swap(0,2): f(c,b,a,d) = -f(a,b,c,d) -/
theorem rank4_swap02 (f : AlternatingMap ℚ M ℚ (Fin 4)) (v : Fin 4 → M) :
    f (v ∘ Equiv.swap 0 2) = -(f v) :=
  f.map_swap v (by decide)

/-- Rank-4 swap(1,3): f(a,d,c,b) = -f(a,b,c,d) -/
theorem rank4_swap13 (f : AlternatingMap ℚ M ℚ (Fin 4)) (v : Fin 4 → M) :
    f (v ∘ Equiv.swap 1 3) = -(f v) :=
  f.map_swap v (by decide)

/-- Rank-4 three-cycle (012→120): even permutation preserves. -/
theorem rank4_cycle3 (f : AlternatingMap ℚ M ℚ (Fin 4)) (v : Fin 4 → M) :
    let σ : Equiv.Perm (Fin 4) := Equiv.swap 0 1 * Equiv.swap 1 2
    f (v ∘ σ) = f v := by
  intro σ
  rw [f.map_perm v σ]
  have : σ.sign = 1 := by decide
  rw [this, one_smul]

/-- Rank-4 four-cycle (0123→1230): odd permutation negates. -/
theorem rank4_cycle4_neg (f : AlternatingMap ℚ M ℚ (Fin 4)) (v : Fin 4 → M) :
    let σ : Equiv.Perm (Fin 4) := Equiv.swap 0 1 * Equiv.swap 1 2 * Equiv.swap 2 3
    f (v ∘ σ) = -(f v) := by
  intro σ
  rw [f.map_perm v σ]
  have : σ.sign = -1 := by decide
  rw [this]
  simp [Units.neg_smul, one_smul]

/-! ## Eval-level identities -/

/-- Eval distributes over addition of symbols. -/
theorem eval_add_syms {k : ℕ} (Γ : Env M k) (a b : String) :
    eval Γ (.app "+" [.sym a, .sym b]) = Γ a + Γ b := by
  simp

/-- Eval of negated symbol. -/
theorem eval_neg_sym {k : ℕ} (Γ : Env M k) (a : String) :
    eval Γ (.app "neg" [.sym a]) = -(Γ a) := by
  simp

/-- Eval of scalar multiple. -/
theorem eval_smul_sym {k : ℕ} (Γ : Env M k) (q : ℚ) (a : String) :
    eval Γ (.app "*" [.lit q, .sym a]) = q • Γ a := by
  simp

/-- Double negation in eval. -/
theorem eval_double_neg {k : ℕ} (Γ : Env M k) (a : String) :
    eval Γ (.app "neg" [.app "neg" [.sym a]]) = Γ a := by
  simp [neg_neg]

/-! ## Discovered by e-graph saturation -/

/-- Discovered: (a + b) + (-b) = a. Not a rule — emergent from associativity + cancellation. -/
theorem eval_add_cancel_right {k : ℕ} (Γ : Env M k) (a b : String) :
    eval Γ (.app "+" [.app "+" [.sym a, .sym b], .app "neg" [.sym b]]) = Γ a := by
  simp [add_assoc, add_neg_cancel, add_zero]

/-- Discovered: (a + b) + (-(a + b)) = 0. Emergent from cancellation on compound expressions. -/
theorem eval_compound_cancel {k : ℕ} (Γ : Env M k) (a b : String) :
    eval Γ (.app "+" [.app "+" [.sym a, .sym b],
                       .app "neg" [.app "+" [.sym a, .sym b]]]) = 0 := by
  simp [add_neg_cancel]

/-- Discovered: -(-(a + b)) = a + b. Double negation on compound expressions. -/
theorem eval_double_neg_compound {k : ℕ} (Γ : Env M k) (a b : String) :
    eval Γ (.app "neg" [.app "neg" [.app "+" [.sym a, .sym b]]]) = Γ a + Γ b := by
  simp [neg_neg]

end Abstractfeld.Tensor
